---
- name: Update APT
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install Docker, Docker Compose, Git
  apt:
    name:
      - docker.io
      - docker-compose
      - git
    state: present

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: true
    state: started

- name: Create app directory
  file:
    path: /home/ubuntu/app
    state: directory
    mode: '0755'

- name: Clone GitHub repository
  git:
    repo: 'https://github.com/YOUR_GITHUB_USERNAME/YOUR_REPO.git'
    dest: /home/ubuntu/app
    version: main       
    force: yes         