version: '3.8'

services:
  app:
    build: ../app
    ports:
      - "3000:3000"
    container_name: resource-app

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    container_name: prometheus

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"   # Host:Container
    container_name: grafana

  node_exporter:
    image: prom/node-exporter
    ports:
      - "9100:9100"
    container_name: node_exporter
