global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'app'
    static_configs:
      - targets: ['app:3000']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
