name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: yourdockerhubusername/systemresourcemonitor

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Image
      run: docker build -t $IMAGE_NAME ./app

    - name: Login to DockerHub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Docker Image
      run: docker push $IMAGE_NAME

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull $IMAGE_NAME
          docker stop resource-app || true
          docker rm resource-app || true
          docker run -d --name resource-app -p 3000:3000 $IMAGE_NAME
